package com.example.usertaskmanager.dto;

import com.example.usertaskmanager.model.TaskStatus;

public class TaskDto {
    private String id; // The unique identifier, usually generated by the database
    private String title;
    private String description;
    private TaskStatus status; // An enum representing the task's state (e.g., PENDING, IN_PROGRESS, COMPLETE)

    // Getters and Setters
    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    public TaskStatus getStatus() { return status; }
    public void setStatus(TaskStatus status) { this.status = status; }
}